### ISSUE TITLE
05_cpp_static_analysis Incorrect Phase

### ISSUE THREAD

**Issue by duncjo** [Submitty/Tutorial#11]
The example of a static C++ analysis given in 05_cpp_static_analysis fails because a "type" parameter is not specified in the test case.  Thus it runs in the default execution phase and source code for compiled languages is not available in that phase.   The addition of the parameter below to the test case will fix the issue.

```
"type" : "Compilation"
```

**Comment by bmcutler** [comment]
Thanks for the nudge.   I actually had an unmerged branch to fix that test (but differently).  I've just merged it.  Rather than moving it to compilation phase, I added lines to copy the files around.  See also:
http://submitty.org/instructor/assignment_configuration

I wonder why this wasn't failing the automated tests on Travis...
